# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44aa374dc164a4e4dc54952d15378fb78d83dd78748904c4df67a739541cf2d64209daa19acb304f58dc400a23b4fd5433cc383a742a88b71750e2adb967859c

test:
  secret_key_base: 6f043d03ef0e26b03ee6ad5dc8165204be257a0fc25cf2b1fe7047eebc5018c93ec8fc1f4edb7b5dfc0a42622367de68ded829007e7ce4b9c23ac587d82a6023

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
